### ISSUE TITLE
Segfault on enrolling when a private key exist but no CSR is present

### ISSUE THREAD

**Issue by smortex** [choria-io/go-choria#1070]
The SNI bugs #1067 resulted in a configuration where only a key is find but no CSR, which cause choria to crash when trying to enroll:

```sh-session
fallout@zappy ~ % tree .puppetlabs
.puppetlabs
└── etc
    └── puppet
        └── ssl
            ├── certificate_requests
            ├── certs
            │   └── ca.pem
            ├── private
            ├── private_keys
            │   └── fallout.mcollective.pem
            └── public_keys

8 directories, 2 files
fallout@zappy ~ % ~romain/Projects/choria-io/go-choria/go-choria enroll -d                    
DEBU[0000] Logging at debug level due to CLI override   
Enrolling with the Security System using certname fallout.mcollective
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11a4505]

goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x438760, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:112 +0x5
crypto/x509.CreateCertificateRequest(0x7789a0, 0xc00003c1e0, 0xc00053f9a0, 0x438760, 0x0, 0x0, 0x34, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/x509/x509.go:2447 +0xbd
github.com/choria-io/go-choria/providers/security/puppetsec.(*PuppetSecurity).writeCSR(0xc000151940, 0x0, 0xc00062ca60, 0x13, 0x54f2f2, 0x9, 0x0, 0x0, 0x0, 0x0)
	/home/romain/Projects/choria-io/go-choria/providers/security/puppetsec/puppet_security.go:448 +0x3b7
github.com/choria-io/go-choria/providers/security/puppetsec.(*PuppetSecurity).Enroll(0xc000151940, 0x7a0a20, 0xc000151880, 0x3a35294400, 0x625828, 0x1, 0x1)
	/home/romain/Projects/choria-io/go-choria/providers/security/puppetsec/puppet_security.go:193 +0x6e5
github.com/choria-io/go-choria/choria.(*Framework).Enroll(...)
	/home/romain/Projects/choria-io/go-choria/choria/ssl.go:22
github.com/choria-io/go-choria/cmd.(*enrollCommand).Run(0xc0001d8840, 0xc00027cf50, 0x0, 0x0)
	/home/romain/Projects/choria-io/go-choria/cmd/enroll.go:44 +0x13f
github.com/choria-io/go-choria/cmd.Run(0x0, 0x0)
	/home/romain/Projects/choria-io/go-choria/cmd/cmd.go:154 +0x357
main.main()
	/home/romain/Projects/choria-io/go-choria/main.go:25 +0x3d
fallout@zappy ~ % rm .puppetlabs/etc/puppet/ssl/private_keys/fallout.mcollective.pem
fallout@zappy ~ % ~romain/Projects/choria-io/go-choria/go-choria enroll -d          
DEBU[0000] Logging at debug level due to CLI override   
Enrolling with the Security System using certname fallout.mcollective
DEBU[0000] Attempting SRV lookup for _x-puppet-ca._tcp.opus-codium.fr 
DEBU[0000] Failed to resolve _x-puppet-ca._tcp.opus-codium.fr: lookup _x-puppet-ca._tcp.opus-codium.fr on 1.1.1.1:53: no such host 
DEBU[0000] Attempting SRV lookup for _x-puppet._tcp.opus-codium.fr 
DEBU[0000] Found 1 SRV records for _x-puppet._tcp.opus-codium.fr 
go-choria: error: Could not enroll: could not submit csr: could not send CSR to https://puppet.opus-codium.fr:8140: 400 Bad Request: fallout.mcollective already has a requested certificate; ignoring certificate request
fallout@zappy ~ % 
```

It is probably the problem I also encountered on Windows where I just removed the `ssl` directory to get quickly back on track.  I think this issue is quite minor since it's the result of an abnormal termination that we are trying to fix, but I open an issue anyway so that we can recall some more safe-checking would be welcome in this area.

**Comment by ripienaar** [comment]
sux, do you want to try this patch for me?

```patch
diff --git a/providers/security/puppetsec/puppet_security.go b/providers/security/puppetsec/puppet_security.go
index 8b9b87e..c46540a 100644
--- a/providers/security/puppetsec/puppet_security.go
+++ b/providers/security/puppetsec/puppet_security.go
@@ -166,7 +166,13 @@ func (s *PuppetSecurity) Enroll(ctx context.Context, wait time.Duration, cb func

        var key *rsa.PrivateKey

-       if !s.privateKeyExists() {
+       if s.privateKeyExists() {
+               s.log.Debugf("Loading existing private key for %s", s.Identity())
+               key, err = s.readPrivateKey()
+               if err != nil {
+                       return fmt.Errorf("could not read private key for %s: %s", s.Identity(), err)
+               }
+       } else {
                s.log.Debugf("Creating a new Private Key %s", s.Identity())

                key, err = s.writePrivateKey()
@@ -632,6 +638,29 @@ func (s *PuppetSecurity) csrTXT() ([]byte, error) {
        return ioutil.ReadFile(s.csrPath())
 }

+func (s *PuppetSecurity) readPrivateKey() (*rsa.PrivateKey, error) {
+       if !s.privateKeyExists() {
+               return nil, fmt.Errorf("key not found in %s", s.privateKeyPath())
+       }
+
+       pd, err := ioutil.ReadFile(s.privateKeyPath())
+       if err != nil {
+               return nil, err
+       }
+
+       privPem, _ := pem.Decode(pd)
+       if privPem.Type != "RSA PRIVATE KEY" {
+               return nil, fmt.Errorf("key file %s did not contain a private key", s.privateKeyPath())
+       }
+
+       parsedKey, err := x509.ParsePKCS1PrivateKey(privPem.Bytes)
+       if err != nil {
+               return nil, err
+       }
+
+       return parsedKey, nil
+}
+
 func (s *PuppetSecurity) writePrivateKey() (*rsa.PrivateKey, error) {
        if s.privateKeyExists() {
                return nil, fmt.Errorf("a private key already exist for %s", s.Identity())
```

**Comment by smortex** [comment]
Works!  I see it is part of b7e8f233, so I'll rebase my PR on top of master and close this isse :+1: 

You rock!

**Comment by ripienaar** [comment]
Ah well, included there by accident lol. But good good
