### ISSUE TITLE
Cannot decode output from Shim for Ruby action

### ISSUE THREAD

**Issue by timhughes** [choria-io/go-choria#1215]
choria-0.18.0-1.el8.x86_64

Choria appears to be unable to handle the output of lots of commands - an exanple is `lsblk` but this affects many commands 
I have noticed it when the command run would contain ansi color codes in it but `lsblk` is an example without color 

```
$ mco rpc shell run command="lsblk" -I some-host01.example.com

 * [ ============================================================> ] 1 / 1


some-host01.example.com              Request Aborted
   Cannot decode output from Shim for Ruby action shell#run: EOF



Finished processing 1 / 1 hosts in 319.45 ms

```

I believe it is hitting this line

https://github.com/choria-io/go-choria/blob/c3fbd2aebffcdf4a0d85df3b67d7abed6147aa2c/providers/agent/mcorpc/ruby/agent.go#L162

**Comment by ripienaar** [comment]
is some-host-1 by any chance a windows machine?

**Comment by timhughes** [comment]
no a linux machine CentOS Linux release 8.3.2011


This is the output when `lsblk` is run on the machine

```NAME                                                 MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                                                    8:0    0  10.7T  0 disk 
└─ceph--333f4b07--be59--40ef--b215--3a28c2af6338-osd--block--4a939998--15a2--4e98--95c3--740442772324
                                                     253:5    0  10.7T  0 lvm  
sdb                                                    8:16   0  10.7T  0 disk 
└─ceph--cfb060f2--df59--46ed--b93d--062656f2df3d-osd--block--6ce6b298--81bc--454d--b7e6--0ad62313e6d6
                                                     253:8    0  10.7T  0 lvm  
sdc                                                    8:32   0  10.7T  0 disk 
└─ceph--9cf35fe0--5f5f--4196--8a67--85a355cc3272-osd--block--aae15893--e4a7--4f10--be82--921c236a4bba
                                                     253:7    0  10.7T  0 lvm  
sdd                                                    8:48   0  10.7T  0 disk 
└─ceph--fbbd36bc--ad9f--41d3--97c6--be19b6964e39-osd--block--b412eb1e--1ba1--436f--a7ba--f5c34c711f4f
                                                     253:6    0  10.7T  0 lvm  
sde                                                    8:64   0  10.7T  0 disk 
└─ceph--f86a5675--81a1--4102--bc4d--f0bb45583e79-osd--block--a43ef1e7--f2eb--4bce--ba33--ce7d70251c6f
                                                     253:10   0  10.7T  0 lvm  
sdf                                                    8:80   0  10.7T  0 disk 
└─ceph--63f5dd71--05eb--4b71--846b--5110a660aee2-osd--block--53d86535--1761--422f--a07a--ee7f0e0ea128
                                                     253:9    0  10.7T  0 lvm  
sdg                                                    8:96   0 446.6G  0 disk 
├─sdg1                                                 8:97   0   200M  0 part /boot/efi
├─sdg2                                                 8:98   0   512M  0 part /boot
└─sdg3                                                 8:99   0   446G  0 part 
  ├─vg_os-lv_root                                    253:0    0     8G  0 lvm  /
  ├─vg_os-lv_swap                                    253:1    0   512M  0 lvm  [SWAP]
  ├─vg_os-lv_sss                                     253:2    0   256M  0 lvm  /var/lib/sss
  ├─vg_os-lv_var_log                                 253:3    0     8G  0 lvm  /var/log
  └─vg_os-images                                     253:4    0   200G  0 lvm  
```

**Comment by timhughes** [comment]
An example of one with ansi color codes is `systemctl`

```$ mco rpc shell run command="systemctl status choria-server.service" -I some-host01.example.com

 * [ ============================================================> ] 1 / 1

some-host01.example.com              Request Aborted
   Cannot decode output from Shim for Ruby action shell#run: EOF



Finished processing 1 / 1 hosts in 320.25 ms```

**Comment by ripienaar** [comment]
OK, the shim has its own logfile, can you see if there's something useful there?

**Comment by timhughes** [comment]
==> /var/log/choria-audit.log <==
```
{"timestamp":"2021-04-09T15:52:53.227975+0000","request_id":"4d534c33513957a49784b10282036bbe","request_time":1617983573,"caller":"choria=hughest.mcollective","sender":"ix3puppet01.example.com","agent":"shell","action":"run","data":{"command":"lsblk","process_results":true}}
```
==> /var/log/choria-mcorpc.log <==
```
I, [2021-04-09T15:52:53.379451 #892935]  INFO -- : config.rb:156:in `loadconfig' The Marionette Collective version 2.22.1 started by /usr/bin/choria_mcollective_agent_compat.rb using config file /etc/puppetlabs/mcollective/choria-shim.cfg
```
==> /var/log/choria.log <==
```
{"agent":"shell","component":"server","identity":"some-host01.example.com","level":"error","msg":"Cannot decode output from Shim for Ruby action shell#run: EOF","subsystem":"agents","time":"2021-04-09T15:52:53Z"}
{"agent":"shell","component":"server","identity":"some-host01.example.com","level":"warning","msg":"Wait call for action shell#run failed: exit status 1","subsystem":"agents","time":"2021-04-09T15:52:53Z"}
```

**Comment by ripienaar** [comment]
OK, so afraid to say debug this is pretty painful, shim crashes and we lose the stderr - i need to log that, I thought I recently made it do so but apparently not.

the last 2 lines of the shim is this:

```
shim = MCollective::AgentShim.new(@options["config"], STDIN.read.chomp)
puts shim.dispatch.to_json
```

change to:

```
begin
  shim = MCollective::AgentShim.new(@options["config"], STDIN.read.chomp)
  puts shim.dispatch.to_json
rescue Exception
  MCollective::Log.error("Shim failed: %s" % [$!.inspect])
  MCollective::Log.error($!.backtrace.join("\n\t\t"))

  puts {"statuscode" => 1, "statusmsg" => "Choria MCollective Compatibility Layer failed to invoke the action: %s" % $!.message, "data" => {}}.to_json
end
```

Also add to `/etc/choria/choria-shim.cfg` the line `loglevel = debug`

**Comment by ripienaar** [comment]
This could still fail badly - but appears at least your log file works, when set to debug confirm there's more logged than just the one line from before

**Comment by timhughes** [comment]
Nothing new logged with that


```
[root@some-host01 ~]# tail -n 20 /usr/bin/choria_mcollective_agent_compat.rb
      {"statuscode" => 1, "statusmsg" => "Choria MCollective Compatibility Layer failed to invoke the action: %s" % $!.message, "data" => {}}
    end
  end
end
begin
  shim = MCollective::AgentShim.new(@options["config"], STDIN.read.chomp)
  
  if @options["parse_compound"]
    puts shim.parse_compound.to_json
  elsif @options["validate_compound"]
    puts shim.match_compound_filter.to_json
  else
    puts shim.dispatch.to_json
  end
rescue Exception
  MCollective::Log.error("Shim failed: %s" % [$!.inspect])
  MCollective::Log.error($!.backtrace.join("\n\t\t"))

  puts {"statuscode" => 1, "statusmsg" => "Choria MCollective Compatibility Layer failed to invoke the action: %s" % $!.message, "data" => {}}.to_json
end
```


```
[root@some-host01 ~]# cat /etc/puppetlabs/mcollective/choria-shim.cfg
classesfile = /opt/puppetlabs/puppet/cache/state/classes.txt
collectives = mcollective
connector = nats
daemonize = 0
factsource = yaml
identity = some-host01.example.com
libdir = /opt/puppetlabs/mcollective/plugins
logfile = /var/log/choria-mcorpc.log
main_collective = mcollective
plugin.choria.srv_domain = example.com
plugin.puppet.command = /opt/puppetlabs/bin/puppet agent
plugin.yaml = /etc/puppetlabs/mcollective/generated-facts.yaml
rpcaudit = 0
rpcauthorization = 1
rpcauthprovider = action_policy
securityprovider = choria
loglevel = debug
```
```
[root@some-host01 ~]# rm -f /var/log/choria*
[root@some-host01 ~]# systemctl restart choria-server.service 
```
```
[root@some-host01 ~]# tail -f  /var/log/choria*
==> /var/log/choria.log <==
{"component":"server","identity":"some-host01.example.com","level":"warning","msg":"External agents are not allowed to supply an agent called 'choria_util', skipping","provider":"external","time":"2021-04-09T16:51:25Z"}
{"component":"server","identity":"some-host01.example.com","level":"warning","msg":"External agents are not allowed to supply an agent called 'rpcutil', skipping","provider":"external","time":"2021-04-09T16:51:25Z"}
{"component":"server","identity":"some-host01.example.com","level":"warning","msg":"External agents are not allowed to supply an agent called 'scout', skipping","provider":"external","time":"2021-04-09T16:51:25Z"}
{"component":"server","identity":"some-host01.example.com","level":"warning","msg":"Ruby agents are not allowed to supply an agent called 'choria_util', skipping","provider":"ruby","time":"2021-04-09T16:51:25Z"}
{"component":"server","identity":"some-host01.example.com","level":"warning","msg":"Ruby agents are not allowed to supply an agent called 'rpcutil', skipping","provider":"ruby","time":"2021-04-09T16:51:25Z"}

==> /var/log/choria-status.json <==
{"identity":"some-host01.example.com","uptime":0,"connected_server":"nats://ix3puppet01.example.com:4222","last_message":0,"provisioning_mode":false,"stats":{"total":0,"valid":0,"invalid":0,"passed":0,"filtered":0,"replies":0,"ttlexpired":0}}
==> /var/log/choria.log <==
{"agent":"shell","component":"server","identity":"some-host01.example.com","level":"error","msg":"Cannot decode output from Shim for Ruby action shell#run: EOF","subsystem":"agents","time":"2021-04-09T16:51:35Z"}
{"agent":"shell","component":"server","identity":"some-host01.example.com","level":"warning","msg":"Wait call for action shell#run failed: exit status 1","subsystem":"agents","time":"2021-04-09T16:51:35Z"}
tail: /var/log/choria-status.json: file truncated

```

**Comment by ripienaar** [comment]
Hmm, the one you have is very old shim, I am not seeing `/var/log/choria-mcorpc.log` in your `choria*` though, is it there and just not shown?

**Comment by timhughes** [comment]
Your are right - something is wrong with my logging - going to have to look next week as it is late on a friday - Thanks for you time.

**Comment by ripienaar** [comment]
Ugh, ok, maybe selinux not allowing new files?

**Comment by timhughes** [comment]
Fixed the logging issue by changing the last couple of lines in the rescue to:
```
  resp = {"statuscode" => 1, "statusmsg" => "Choria MCollective Compatibility Layer failed to invoke the action: %s" % $!.message, "data" => {}}
  puts resp.to_json
```


This is the error 

```mco rpc shell run command="lsblk" -I some-host01.example.com

 * [ ============================================================> ] 1 / 1


some-host01.example.com              Request Aborted
   Choria MCollective Compatibility Layer failed to invoke the action: "\xE2" from ASCII-8BIT to UTF-8



Finished processing 1 / 1 hosts in 331.62 ms
```

And this is the logs
```
D, [2021-04-12T11:23:25.297309 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading Mcollective::Facts::Yaml_facts from mcollective/facts/yaml_facts.rb
D, [2021-04-12T11:23:25.309873 #45544] DEBUG -- : pluginmanager.rb:43:in `<<' Registering plugin facts_plugin with class MCollective::Facts::Yaml_facts single_instance: true
D, [2021-04-12T11:23:25.309927 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading Mcollective::Connector::Nats from mcollective/connector/nats.rb
D, [2021-04-12T11:23:25.335123 #45544] DEBUG -- : cache.rb:117:in `block in ttl' Cache miss on 'ddl' key 'connector/nats'
D, [2021-04-12T11:23:25.335207 #45544] DEBUG -- : base.rb:101:in `block in findddlfile' Found nats ddl at /opt/puppetlabs/mcollective/plugins/mcollective/connector/nats.ddl
D, [2021-04-12T11:23:25.335305 #45544] DEBUG -- : pluginmanager.rb:43:in `<<' Registering plugin connector_plugin with class MCollective::Connector::Nats single_instance: true
D, [2021-04-12T11:23:25.335349 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading Mcollective::Security::Choria from mcollective/security/choria.rb
D, [2021-04-12T11:23:25.336904 #45544] DEBUG -- : pluginmanager.rb:43:in `<<' Registering plugin security_plugin with class MCollective::Security::Choria single_instance: true
D, [2021-04-12T11:23:25.336966 #45544] DEBUG -- : pluginmanager.rb:46:in `<<' Registering plugin global_stats with class MCollective::RunnerStats single_instance: true
I, [2021-04-12T11:23:25.336991 #45544]  INFO -- : config.rb:156:in `loadconfig' The Marionette Collective version 2.22.1 started by /usr/bin/choria_mcollective_agent_compat.rb using config file /etc/puppetlabs/mcollective/choria-shim.cfg
D, [2021-04-12T11:23:25.337182 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Agent::Shell from mcollective/agent/shell.rb
D, [2021-04-12T11:23:25.339830 #45544] DEBUG -- : agent.rb:143:in `activate?' Starting default activation checks for shell
D, [2021-04-12T11:23:25.339891 #45544] DEBUG -- : cache.rb:117:in `block in ttl' Cache miss on 'ddl' key 'agent/shell'
D, [2021-04-12T11:23:25.339951 #45544] DEBUG -- : base.rb:101:in `block in findddlfile' Found shell ddl at /opt/puppetlabs/mcollective/plugins/mcollective/agent/shell.ddl
D, [2021-04-12T11:23:25.340274 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Util::ActionPolicy from mcollective/util/actionpolicy.rb
D, [2021-04-12T11:23:25.341111 #45544] DEBUG -- : choria_mcollective_agent_compat.rb:143:in `dispatch' Dispatching request e9dee08be51454569db6f393ed330129 from choria=timhughes.mcollective@ix3puppet01.example.com to shell#run
D, [2021-04-12T11:23:25.341490 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Array_validator from mcollective/validator/array_validator.rb
D, [2021-04-12T11:23:25.341646 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Ipaddress_validator from mcollective/validator/ipaddress_validator.rb
D, [2021-04-12T11:23:25.343486 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Ipv4address_validator from mcollective/validator/ipv4address_validator.rb
D, [2021-04-12T11:23:25.343680 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Ipv6address_validator from mcollective/validator/ipv6address_validator.rb
D, [2021-04-12T11:23:25.343856 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Length_validator from mcollective/validator/length_validator.rb
D, [2021-04-12T11:23:25.344009 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Nettest_fqdn from mcollective/validator/nettest_fqdn.rb
D, [2021-04-12T11:23:25.344170 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Nettest_server_address from mcollective/validator/nettest_server_address.rb
D, [2021-04-12T11:23:25.344381 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Package_name from mcollective/validator/package_name.rb
D, [2021-04-12T11:23:25.344521 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Puppet_resource_validator from mcollective/validator/puppet_resource_validator.rb
D, [2021-04-12T11:23:25.344649 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Puppet_server_address_validator from mcollective/validator/puppet_server_address_validator.rb
D, [2021-04-12T11:23:25.345084 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Puppet_tags_validator from mcollective/validator/puppet_tags_validator.rb
D, [2021-04-12T11:23:25.345232 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Puppet_variable_validator from mcollective/validator/puppet_variable_validator.rb
D, [2021-04-12T11:23:25.345382 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Regex_validator from mcollective/validator/regex_validator.rb
D, [2021-04-12T11:23:25.345543 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Service_name from mcollective/validator/service_name.rb
D, [2021-04-12T11:23:25.345667 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Shellsafe_validator from mcollective/validator/shellsafe_validator.rb
D, [2021-04-12T11:23:25.345836 #45544] DEBUG -- : pluginmanager.rb:164:in `loadclass' Loading MCollective::Validator::Typecheck_validator from mcollective/validator/typecheck_validator.rb
D, [2021-04-12T11:23:25.346070 #45544] DEBUG -- : actionpolicy.rb:256:in `lookup_policy_file' Looking for policy in /etc/puppetlabs/mcollective/policies/shell.policy
D, [2021-04-12T11:23:25.346124 #45544] DEBUG -- : actionpolicy.rb:93:in `parse_group_file' Parsing groups file /etc/puppetlabs/mcollective/policies/groups
D, [2021-04-12T11:23:25.346192 #45544] DEBUG -- : actionpolicy.rb:52:in `parse_policy_file' Parsing policyfile for shell: /etc/puppetlabs/mcollective/policies/shell.policy
E, [2021-04-12T11:23:25.493967 #45544] ERROR -- : choria_mcollective_agent_compat.rb:177:in `rescue in <main>' Shim failed: #<Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8>
E, [2021-04-12T11:23:25.494048 #45544] ERROR -- : choria_mcollective_agent_compat.rb:178:in `rescue in <main>' /usr/bin/choria_mcollective_agent_compat.rb:174:in `encode'
                /usr/bin/choria_mcollective_agent_compat.rb:174:in `to_json'
                /usr/bin/choria_mcollective_agent_compat.rb:174:in `<main>'
```

**Comment by ripienaar** [comment]
Ok so this is likely due to code pages. Ultimately the JSON we send around is not the same code page as what is parses from your command. 

We had this before - but I can’t find it now while on mobile - I think the answer was to set LC_ALL=C when starting choria server. You can do this using a systemd override without requiring a change to the files the package owns

**Comment by timhughes** [comment]
Thanks  - that fixed it. 

I did `systemctl edit choria-server.service` and added in:

```
[Service]
Environment="LC_ALL=C"
```

Restarted choria-server and then everything worked

**Comment by ripienaar** [comment]
Please share the last few lines of your wrapper. Maybe I can improve ours so we can stop struggling so much if you have a better capture code for the error there

**Comment by timhughes** [comment]
it is exactly what you gave me initially apart from splitting the hash creation and to_json into two statements 

```begin
  shim = MCollective::AgentShim.new(@options["config"], STDIN.read.chomp)
  puts shim.dispatch.to_json
rescue Exception
  MCollective::Log.error("Shim failed: %s" % [$!.inspect])
  MCollective::Log.error($!.backtrace.join("\n\t\t"))
  resp = {"statuscode" => 1, "statusmsg" => "Choria MCollective Compatibility Layer failed to invoke the action: %s" % $!.message, "data" => {}}
  puts resp.to_json
end
```

**Comment by ripienaar** [comment]
OK, the logging failure was actually pretty crazy - it would exceed the maximum stack and so result in an untrapable error, which explains why existing error handling wasnt sufficient.  I fixed that problem so now the shim will work even without logging.
