### ISSUE TITLE
 Cannot decode output from Shim for Ruby action puppet#status: EOF

### ISSUE THREAD

**Issue by opslx** [choria-io/go-choria#1421]
[foreman@foreman log]$ mco puppet status

 * [ ================================> ] 3 / 3

               node1: Cannot decode output from Shim for Ruby action puppet#status: EOF
               node2: Cannot decode output from Shim for Ruby action puppet#status: EOF
   foreman.dobest.cn: Currently idling; last completed run 6 minutes 28 seconds ago

Summary of Applying:

   false = 1

Summary of Daemon Running:

   running = 1

Summary of Enabled:

   enabled = 1

Summary of Idling:

   true = 1

Summary of Status:

   idling = 1

Finished processing 3 / 3 hosts in 2645.19 ms

foreman.dobest.cn is   puppetserver and choria-broker,server   ，node1 and node2 is choria-server ， why node error?

**Comment by ripienaar** [comment]
Can you take a look at the server logs on those machines pls

**Comment by opslx** [comment]
[root@node2 log]# cat choria.log 
```
{"component":"server","identity":"node2","level":"debug","msg":"Writing server status to /var/log/choria-status.json","time":"2021-09-15T09:46:46Z"}
{"component":"security","level":"debug","msg":"Already have a certificate in /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem, refusing to overwrite with a new one","ssl":"file","time":"2021-09-15T09:47:06Z"}
{"component":"security","level":"debug","msg":"Attempting to verify signature for foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:06Z"}
{"component":"security","level":"debug","msg":"Verified signature from foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:06Z"}
{"component":"security","level":"debug","msg":"Allowing certificate foreman.mcollective to act as foreman.mcollective","ssl":"file","time":"2021-09-15T09:47:06Z"}
{"component":"discovery","level":"debug","msg":"Matching request d339bb47782642e09d4a3691edbd53a9 with agent filters '[]string{\"puppet\", \"rpcutil\"}'","request":"d339bb47782642e09d4a3691edbd53a9","subsystem":"discovery","time":"2021-09-15T09:47:06Z"}
{"component":"server","identity":"node2","level":"debug","msg":"Handling message d339bb47782642e09d4a3691edbd53a9 with timeout 2000000000","subsystem":"agents","time":"2021-09-15T09:47:06Z"}
{"agent":"discovery","component":"server","identity":"node2","level":"info","msg":"Handling message d339bb47782642e09d4a3691edbd53a9 for discovery#ping from choria=foreman.mcollective","subsystem":"agents","time":"2021-09-15T09:47:06Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Sending a broadcast message to NATS target 'mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.d339bb47782642e09d4a3691edbd53a9' for message d339bb47782642e09d4a3691edbd53a9 type reply","time":"2021-09-15T09:47:06Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Publishing 549 bytes to mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.d339bb47782642e09d4a3691edbd53a9","time":"2021-09-15T09:47:06Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Flushing pending NATS messages","time":"2021-09-15T09:47:06Z"}
{"component":"security","level":"debug","msg":"Already have a certificate in /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem, refusing to overwrite with a new one","ssl":"file","time":"2021-09-15T09:47:08Z"}
{"component":"security","level":"debug","msg":"Attempting to verify signature for foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:08Z"}
{"component":"security","level":"debug","msg":"Verified signature from foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:08Z"}
{"component":"security","level":"debug","msg":"Allowing certificate foreman.mcollective to act as foreman.mcollective","ssl":"file","time":"2021-09-15T09:47:08Z"}
{"component":"discovery","level":"debug","msg":"Matching request 1351d257086f59be9e5a94b3973bd2db with agent filters '[]string{\"puppet\"}'","request":"1351d257086f59be9e5a94b3973bd2db","subsystem":"discovery","time":"2021-09-15T09:47:08Z"}
{"component":"server","identity":"node2","level":"debug","msg":"Handling message 1351d257086f59be9e5a94b3973bd2db with timeout 20000000000","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"agent":"puppet","authorizer":"actionpolicy","component":"server","identity":"node2","level":"debug","msg":"Looking up agent policy in /etc/choria/policies/puppet.policy","request":"1351d257086f59be9e5a94b3973bd2db","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"agent":"puppet","authorizer":"actionpolicy","component":"server","identity":"node2","level":"debug","msg":"Parsing policy /etc/choria/policies/puppet.policy","request":"1351d257086f59be9e5a94b3973bd2db","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"agent":"puppet","authorizer":"actionpolicy","component":"server","identity":"node2","level":"debug","msg":"found default allow line: policy default allow","request":"1351d257086f59be9e5a94b3973bd2db","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"agent":"puppet","component":"server","identity":"node2","level":"info","msg":"Handling message 1351d257086f59be9e5a94b3973bd2db for puppet#runonce from choria=foreman.mcollective","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"agent":"puppet","component":"server","identity":"node2","level":"debug","msg":"Attempting to call Ruby agent puppet#runonce with a timeout 20","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"agent":"puppet","component":"server","identity":"node2","level":"error","msg":"Cannot decode output from Shim for Ruby action puppet#runonce: EOF","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"agent":"puppet","component":"server","identity":"node2","level":"warning","msg":"Wait call for action puppet#runonce failed: exit status 1","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Sending a broadcast message to NATS target 'mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.3584.1' for message 1351d257086f59be9e5a94b3973bd2db type reply","time":"2021-09-15T09:47:08Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Publishing 757 bytes to mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.3584.1","time":"2021-09-15T09:47:08Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Flushing pending NATS messages","time":"2021-09-15T09:47:08Z"}
{"component":"server","identity":"node2","level":"debug","msg":"Writing server status to /var/log/choria-status.json","time":"2021-09-15T09:47:16Z"}
{"component":"security","level":"debug","msg":"Already have a certificate in /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem, refusing to overwrite with a new one","ssl":"file","time":"2021-09-15T09:47:29Z"}
{"component":"security","level":"debug","msg":"Attempting to verify signature for foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:29Z"}
{"component":"security","level":"debug","msg":"Verified signature from foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:29Z"}
{"component":"security","level":"debug","msg":"Allowing certificate foreman.mcollective to act as foreman.mcollective","ssl":"file","time":"2021-09-15T09:47:29Z"}
{"component":"discovery","level":"debug","msg":"Matching request cd782533b1454b068f59fac911bf106b with agent filters '[]string{\"service\", \"rpcutil\"}'","request":"cd782533b1454b068f59fac911bf106b","subsystem":"discovery","time":"2021-09-15T09:47:29Z"}
{"component":"server","identity":"node2","level":"debug","msg":"Handling message cd782533b1454b068f59fac911bf106b with timeout 2000000000","subsystem":"agents","time":"2021-09-15T09:47:29Z"}
{"agent":"discovery","component":"server","identity":"node2","level":"info","msg":"Handling message cd782533b1454b068f59fac911bf106b for discovery#ping from choria=foreman.mcollective","subsystem":"agents","time":"2021-09-15T09:47:29Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Sending a broadcast message to NATS target 'mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.cd782533b1454b068f59fac911bf106b' for message cd782533b1454b068f59fac911bf106b type reply","time":"2021-09-15T09:47:29Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Publishing 549 bytes to mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.cd782533b1454b068f59fac911bf106b","time":"2021-09-15T09:47:29Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Flushing pending NATS messages","time":"2021-09-15T09:47:29Z"}
{"component":"security","level":"debug","msg":"Already have a certificate in /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem, refusing to overwrite with a new one","ssl":"file","time":"2021-09-15T09:47:30Z"}
{"component":"security","level":"debug","msg":"Attempting to verify signature for foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:30Z"}
{"component":"security","level":"debug","msg":"Verified signature from foreman.mcollective using /etc/puppetlabs/puppet/ssl/choria_security/public_certs/foreman.mcollective.pem","ssl":"file","time":"2021-09-15T09:47:30Z"}
{"component":"security","level":"debug","msg":"Allowing certificate foreman.mcollective to act as foreman.mcollective","ssl":"file","time":"2021-09-15T09:47:30Z"}
{"component":"discovery","level":"debug","msg":"Matching request 78182dc7a58b5408a66bc3b6ac89d970 with agent filters '[]string{\"service\"}'","request":"78182dc7a58b5408a66bc3b6ac89d970","subsystem":"discovery","time":"2021-09-15T09:47:30Z"}
{"component":"server","identity":"node2","level":"debug","msg":"Handling message 78182dc7a58b5408a66bc3b6ac89d970 with timeout 60000000000","subsystem":"agents","time":"2021-09-15T09:47:30Z"}
{"agent":"service","authorizer":"actionpolicy","component":"server","identity":"node2","level":"debug","msg":"Looking up agent policy in /etc/choria/policies/service.policy","request":"78182dc7a58b5408a66bc3b6ac89d970","subsystem":"agents","time":"2021-09-15T09:47:30Z"}
{"agent":"service","authorizer":"actionpolicy","component":"server","identity":"node2","level":"debug","msg":"Parsing policy /etc/choria/policies/service.policy","request":"78182dc7a58b5408a66bc3b6ac89d970","subsystem":"agents","time":"2021-09-15T09:47:30Z"}
{"agent":"service","authorizer":"actionpolicy","component":"server","identity":"node2","level":"debug","msg":"found default allow line: policy default allow","request":"78182dc7a58b5408a66bc3b6ac89d970","subsystem":"agents","time":"2021-09-15T09:47:30Z"}
{"agent":"service","component":"server","identity":"node2","level":"info","msg":"Handling message 78182dc7a58b5408a66bc3b6ac89d970 for service#status from choria=foreman.mcollective","subsystem":"agents","time":"2021-09-15T09:47:30Z"}
{"agent":"service","component":"server","identity":"node2","level":"debug","msg":"Attempting to call Ruby agent service#status with a timeout 60","subsystem":"agents","time":"2021-09-15T09:47:30Z"}
{"agent":"service","component":"server","identity":"node2","level":"error","msg":"Cannot decode output from Shim for Ruby action service#status: EOF","subsystem":"agents","time":"2021-09-15T09:47:31Z"}
{"agent":"service","component":"server","identity":"node2","level":"warning","msg":"Wait call for action service#status failed: exit status 1","subsystem":"agents","time":"2021-09-15T09:47:31Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Sending a broadcast message to NATS target 'mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.3705.1' for message 78182dc7a58b5408a66bc3b6ac89d970 type reply","time":"2021-09-15T09:47:31Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Publishing 757 bytes to mcollective.reply.93a020e41005cf11fe0b0c9762851dbe.3705.1","time":"2021-09-15T09:47:31Z"}
{"component":"server","connection":"node2","identity":"node2","level":"debug","msg":"Flushing pending NATS messages","time":"2021-09-15T09:47:31Z"}
{"component":"server","identity":"node2","level":"debug","msg":"Writing server status to /var/log/choria-status.json","time":"2021-09-15T09:47:46Z"}
```
[root@node2 log]# cat choria-audit.log
```
esults":true}}
{"timestamp":"2021-09-15T09:29:29.190836+0000","request_id":"b13d058c529d57aea535677adb685bba","request_time":1631698169,"caller":"choria=foreman.mcollective","sender":"foreman.dobest.cn","agent":"puppet","action":"status","data":{"process_results":true}}
{"timestamp":"2021-09-15T09:31:37.493648+0000","request_id":"6a105711d8a5557085172c2e93947057","request_time":1631698297,"caller":"choria=foreman.mcollective","sender":"foreman.dobest.cn","agent":"puppet","action":"status","data":{"process_results":true}}
{"timestamp":"2021-09-15T09:36:52.871141+0000","request_id":"e0708ace97045dc688f02690d6597343","request_time":1631698612,"caller":"choria=foreman.mcollective","sender":"foreman.dobest.cn","agent":"puppet","action":"status","data":{"process_results":true}}
{"timestamp":"2021-09-15T09:47:08.105253+0000","request_id":"1351d257086f59be9e5a94b3973bd2db","request_time":1631699228,"caller":"choria=foreman.mcollective","sender":"foreman.dobest.cn","agent":"puppet","action":"runonce","data":{"process_results":true}}
{"timestamp":"2021-09-15T09:47:30.933858+0000","request_id":"78182dc7a58b5408a66bc3b6ac89d970","request_time":1631699250,"caller":"choria=foreman.mcollective","sender":"foreman.dobest.cn","agent":"service","action":"status","data":{"service":"puppet","process_results":true}}
```
[root@node2 log]# cat /etc/redhat-release 
CentOS Linux release 8.3.2011

but node2 and node1  not have /var/log/choria-mcorpc.log

**Comment by ripienaar** [comment]
OK, sadly not much info, it's a bit of a pain to debug.  What version choria is this? I did add some additional logging here recently I thought:

```
{"agent":"puppet","component":"server","identity":"node2","level":"error","msg":"Cannot decode output from Shim for Ruby action puppet#runonce: EOF","subsystem":"agents","time":"2021-09-15T09:47:08Z"}
```

**Comment by opslx** [comment]
[root@node2 log]# choria --version
0.23.0

[foreman@foreman log]$ mco
The Marionette Collective version 2.24.1

**Comment by ripienaar** [comment]
ok, so as root do this:

```
$ cd /
$ echo '{"agent":"puppet","action":"status","requestid":"b4a7bd9b22cd4c42a6845c3f873cfc16","senderid":"p1-lon","callerid":"choria=rip.mcollective","collective":"mcollective","ttl":60,"msgtime":1631699979,"body":{"agent":"puppet","action":"status","data":{},"caller":"choria=rip.mcollective"}}'|/usr/bin/choria_mcollective_agent_compat.rb --config /etc/choria/choria-shim.cfg
```

it essentially invokes puppet status action via the shim, lets see what it says

**Comment by opslx** [comment]
[root@node2 /]# echo '{"agent":"puppet","action":"status","requestid":"b4a7bd9b22cd4c42a6845c3f873cfc16","senderid":"p1-lon","callerid":"choria=rip.mcollective","collective":"mcollective","ttl":60,"msgtime":1631699979,"body":{"agent":"puppet","action":"status","data":{},"caller":"choria=rip.mcollective"}}'|/usr/bin/choria_mcollective_agent_compat.rb --config /etc/choria/choria-shim.cfg
Traceback (most recent call last):
	2: from /usr/bin/choria_mcollective_agent_compat.rb:3:in `<main>'
	1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- mcollective (LoadError)

**Comment by ripienaar** [comment]
so this appear these machines are not correctly installed, perhaps missing the `choria-mcorpc-support` gem check with `/opt/puppetlabs/puppet/bin/gem list|grep mco`

**Comment by ripienaar** [comment]
Also this appears to be using the wrong ruby, not the one from puppet-agent

**Comment by opslx** [comment]
Thank you, maybe I need to check the documentation to reinstall

**Comment by ripienaar** [comment]
could be you installed `puppet` rpm and not the puppetlabs `puppet-agent` one or similar?

**Comment by opslx** [comment]
Yes Im yum install epel-release  and yum install puppet

**Comment by ripienaar** [comment]
Cool, should be puppet-agent from puppetlabs repos.

**Comment by opslx** [comment]
Thank you, This is great
