### ISSUE TITLE
buildinfo segfaults

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#308]
```
choria buildinfo
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7c950b]

goroutine 1 [running]:
github.com/choria-io/go-choria/choria.(*Framework).SetupLogging(0xc42012d140, 0xc420134200, 0xa065e0, 0x1)
        /Users/rip/go/src/github.com/choria-io/go-choria/choria/framework.go:239 +0xfb
github.com/choria-io/go-choria/choria.NewWithConfig(0x0, 0xade0d8, 0xb316c0, 0xc420138440)
        /Users/rip/go/src/github.com/choria-io/go-choria/choria/framework.go:52 +0xec
github.com/choria-io/go-choria/cmd.Run(0x0, 0x0)
        /Users/rip/go/src/github.com/choria-io/go-choria/cmd/cmd.go:92 +0xfa
main.main()
        /Users/rip/go/src/github.com/choria-io/go-choria/main.go:22 +0x3d
```

https://github.com/choria-io/go-choria/blob/master/cmd/cmd.go#L51-L55

Needs to happen after `cfg` is set

**Comment by ripienaar** [comment]
```
[rip@dev2]% choria buildinfo
Choria build settings:

Build Data:
     Version: 0.99.0.20180527
     Git SHA: 4831f40eb211ec6bcb2a27a5e31cfa4c148f77e5
  Build Date: 2018-05-27 00:02:19 +0000
     License: Apache-2.0
  Go Version: go1.10

Network Broker Settings:
       Maximum Network Clients: 50000
  Embedded NATS Server Version: 1.1.0

Server Settings:
        Provisioning Brokers:
        Provisioning Default: false
  Default Provisioning Agent: true

Agent Providers:
        Golang MCollective Agent Compatibility version 0.99.0.20180527
        Ruby MCollective Agent Compatibility version 0.99.0.20180527

Security Defaults:
            TLS: true
  x509 Security: true
```
